HaSSL: Information_Access_Manager::TechnologyAdapter Class Reference
Information_Access_Manager::TechnologyAdapter Class Reference abstract
#include <TechnologyAdapter.hpp>
Public Member Functions
bool setBuildingAndRegistrationInterface (std::shared_ptr< Information_Model_Static_Part::BuildingAndRegistrationInterface > building_and_registration_interface)
TechnologyAdapter (std::string name)
virtual bool start ()=0
virtual bool isRunning ()=0
virtual void BuildingAndRegistrationInterfaceWasSet ()=0
virtual bool stop ()=0
AbstractionFactory * getAbstractionFactory ()
~TechnologyAdapter ()
Private Attributes
std::string adapter_name_
AbstractionFactory * abstraction_factory_
Constructor & Destructor Documentation
TechnologyAdapter()
Information_Access_Manager::TechnologyAdapter::TechnologyAdapter (std::string name) inline
References abstraction_factory_, BuildingAndRegistrationInterfaceWasSet(), isRunning(), start(), and stop().
~TechnologyAdapter()
Information_Access_Manager::TechnologyAdapter::~TechnologyAdapter () inline
References abstraction_factory_.
Member Function Documentation
BuildingAndRegistrationInterfaceWasSet()
virtual void Information_Access_Manager::TechnologyAdapter::BuildingAndRegistrationInterfaceWasSet () pure virtual
Referenced by setBuildingAndRegistrationInterface(), and TechnologyAdapter().
getAbstractionFactory()
AbstractionFactory* Information_Access_Manager::TechnologyAdapter::getAbstractionFactory () inline
References abstraction_factory_.
isRunning()
virtual bool Information_Access_Manager::TechnologyAdapter::isRunning () pure virtual
Referenced by TechnologyAdapter().
setBuildingAndRegistrationInterface()
bool Information_Access_Manager::TechnologyAdapter::setBuildingAndRegistrationInterface (std::shared_ptr< Information_Model_Static_Part::BuildingAndRegistrationInterface > building_and_registration_interface) inline
References abstraction_factory_, and BuildingAndRegistrationInterfaceWasSet().
start()
virtual bool Information_Access_Manager::TechnologyAdapter::start () pure virtual
Referenced by TechnologyAdapter().
stop()
virtual bool Information_Access_Manager::TechnologyAdapter::stop () pure virtual
Referenced by TechnologyAdapter().
Field Documentation
abstraction_factory_
AbstractionFactory* Information_Access_Manager::TechnologyAdapter::abstraction_factory_ private
Referenced by getAbstractionFactory(), setBuildingAndRegistrationInterface(), TechnologyAdapter(), and ~TechnologyAdapter().
adapter_name_
std::string Information_Access_Manager::TechnologyAdapter::adapter_name_ private
The documentation for this class was generated from the following file:
TechnologyAdapter.hpp